## Dot product example (nut butter sales)

In [8]:
import numpy as np
import pandas as pd

In [6]:
np.random.seed(0)
#number of jars sold
sales_amounts =  np.random.randint(20 , size= (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [12]:
# creating weekly_sales dataframe

weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues" , "Wed", "Thurs", "Fri"],
                           columns =["Almond", "Peanut butter" , "Cashew butter"])
weekly_sales

       Almond  Peanut butter  Cashew butter
Mon        12             15              0
Tues        3              3              7
Wed         9             19             18
Thurs       4              6             12
Fri         1              6              7

In [16]:
# creating prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [18]:
#creating butter prices Dataframe
butter_prices = pd.DataFrame(prices, index = ["Price"],
                             columns = ["Almond", "Peanut butter" , "Cashew butter"])
butter_prices

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [20]:
prices.shape

(3,)

In [22]:
#creating butter prices Dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index = ["Price"],
                             columns = ["Almond", "Peanut butter" , "Cashew butter"])
butter_prices

       Almond  Peanut butter  Cashew butter
Price      10              8             12

In [24]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [26]:
sales_amounts.shape

(5, 3)

In [28]:
prices.shape

(3,)

In [32]:
#since shapes aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [34]:
# create daily_sales
butter_prices.shape , weekly_sales.shape

((1, 3), (5, 3))

In [36]:
daily_sales= butter_prices.dot(weekly_sales.T)
daily_sales

       Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [38]:
weekly_sales

       Almond  Peanut butter  Cashew butter
Mon        12             15              0
Tues        3              3              7
Wed         9             19             18
Thurs       4              6             12
Fri         1              6              7

In [40]:
weekly_sales["Total ($)"] = daily_sales.T

In [42]:
weekly_sales

       Almond  Peanut butter  Cashew butter  Total ($)
Mon        12             15              0        240
Tues        3              3              7        138
Wed         9             19             18        458
Thurs       4              6             12        232
Fri         1              6              7        142

# we have made a table from scratch exactly like the example